In [76]:
import pandas as pd
import numpy as np

In [77]:
stretch_data = pd.read_csv("gym/stretch_exercise_dataset.csv")
stretch_data.head()

,Exercise Name,Equipment,Preparation,Execution,Target_Muscles,Synergist_Muscles,Main_muscle
0,Retraction​​​​​​​,Stretch,Stand or sit.,Pull head back as far possible while looking s...,"Longus colli,","Splenius, Trapezius, Upper, Erector Spinae, Ce...",Neck
1,Neck Extensor,Stretch,Bow head forward with jaw shut. Depress chin i...,Slightly turn head to one side. Hold stretch. ...,"Splenius,","Trapezius, Upper (Part 1), Erector Spinae, Cer...",Neck
2,Doorway,Stretch,NaN,NaN,"Deltoid, Anterior,","Pectoralis Major, Sternal, Pectoralis Major, C...",Shoulder
3,Wall,Stretch,NaN,NaN,"Deltoid, Anterior,","Pectoralis Major, Sternal, Pectoralis Major, C...",Shoulder
4,Side Deltoid,Stretch,NaN,NaN,"Deltoid, Lateral,","Infraspinatus, Teres Minor, Trapezius, Middle,...",Shoulder

In [78]:
stretch_data.columns

Index(['Exercise Name', 'Equipment', 'Preparation', 'Execution',
       'Target_Muscles', 'Synergist_Muscles', 'Main_muscle'],
      dtype='object')

In [79]:
sleep_data = pd.read_csv("sleep/ss.csv")
sleep_data.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [80]:
print(sleep_data.info())
print(sleep_data.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 373 entries, 0 to 372
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Person ID                373 non-null    int64
 1   Gender                   373 non-null    object
 2   Age                      373 non-null    int64
 3   Occupation               373 non-null    object
 4   Sleep Duration           373 non-null    float64
 5   Quality of Sleep         373 non-null    int64
 6   Physical Activity Level  373 non-null    int64
 7   Stress Level             373 non-null    int64
 8   BMI Category             373 non-null    object
 9   Blood Pressure           373 non-null    object
 10  Heart Rate               373 non-null    int64
 11  Daily Steps              373 non-null    int64
 12  Sleep Disorder           154 non-null    object
dtypes: float64(1), int64(7), object(5)
memory usage: 38.0+ KB
None
        Person ID         Age  Sleep Duration  Quality of Sleep  \
count  373.000000  373.000000      373.000000        373.000000
mean   187.000000   42.139410        7.129491          7.308311
std    107.820066    8.640793        0.795139          1.195359
min      1.000000   27.000000        5.800000          4.000000
25%     94.000000   35.000000        6.400000          6.000000
50%    187.000000   43.000000        7.200000          7.000000
75%    280.000000   50.000000        7.800000          8.000000
max    373.000000   59.000000        8.500000          9.000000

       Physical Activity Level  Stress Level  Heart Rate   Daily Steps
count               373.000000    373.000000  373.000000    373.000000
mean                 59.128686      5.391421   70.171582   6816.353887
std                  20.842589      1.772590    4.139704   1620.060932
min                  30.000000      3.000000   65.000000   3000.000000
25%                  45.000000      4.000000   68.000000   5600.000000
50%                  60.000000      5.000000   70.000000   7000.000000
75%                  75.000000      7.000000   72.000000   8000.000000
max                  90.000000      8.000000   86.000000  10000.000000

In [81]:

print(sleep_data.isnull().sum())

Person ID                    0
Gender                       0
Age                          0
Occupation                   0
Sleep Duration               0
Quality of Sleep             0
Physical Activity Level      0
Stress Level                 0
BMI Category                 0
Blood Pressure               0
Heart Rate                   0
Daily Steps                  0
Sleep Disorder             219
dtype: int64

In [82]:

# print(sleep_data.isnull().sum())
sleep_data['Gender'] = sleep_data['Gender'].map({'Male': 0, 'Female': 1})
# sleep_data = sleep_data.fillna(sleep_data.median())
# print(sleep_data.isnull().sum())
sleep_data['Gender']
# print(diet_data.isnull().sum())
# print(diet_nutri_data.isnull().sum())

0      0
1      0
2      0
3      0
4      0
      ..
368    1
369    1
370    1
371    1
372    1
Name: Gender, Length: 373, dtype: int64

In [83]:
sleep_data['Occupation'].unique()

array(['Software Engineer', 'Doctor', 'Sales Representative', 'Teacher',
       'Nurse', 'Engineer', 'Accountant', 'Scientist', 'Lawyer',
       'Salesperson', 'Manager'], dtype=object)

In [84]:
#Male and Female count in dataset
sleep_data['Gender'].value_counts()

Gender
0    189
1    184
Name: count, dtype: int64

In [85]:
print(sleep_data.isnull().sum())

Person ID                    0
Gender                       0
Age                          0
Occupation                   0
Sleep Duration               0
Quality of Sleep             0
Physical Activity Level      0
Stress Level                 0
BMI Category                 0
Blood Pressure               0
Heart Rate                   0
Daily Steps                  0
Sleep Disorder             219
dtype: int64

In [86]:
sleep_data['Sleep Disorder'] = sleep_data['Sleep Disorder'].fillna('No Disorder')

In [87]:
print(sleep_data.isnull().sum())

Person ID                  0
Gender                     0
Age                        0
Occupation                 0
Sleep Duration             0
Quality of Sleep           0
Physical Activity Level    0
Stress Level               0
BMI Category               0
Blood Pressure             0
Heart Rate                 0
Daily Steps                0
Sleep Disorder             0
dtype: int64

In [88]:
sleep_data.head(n=50)

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,0,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,No Disorder
1,2,0,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,No Disorder
2,3,0,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,No Disorder
3,4,0,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,0,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
5,6,0,28,Software Engineer,5.9,4,30,8,Obese,140/90,85,3000,Insomnia
6,7,0,29,Teacher,6.3,6,40,7,Obese,140/90,82,3500,Insomnia
7,8,0,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,No Disorder
8,9,0,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,No Disorder
9,10,0,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,No Disorder
10,11,0,29,Doctor,6.1,6,30,8,Normal,120/80,70,8000,No Disorder
11,12,0,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,No Disorder
12,13,0,29,Doctor,6.1,6,30,8,Normal,120/80,70,8000,No Disorder
13,14,0,29,Doctor,6.0,6,30,8,Normal,120/80,70,8000,No Disorder
14,15,0,29,Doctor,6.0,6,30,8,Normal,120/80,70,8000,No Disorder
15,16,0,29,Doctor,6.0,6,30,8,Normal,120/80,70,8000,No Disorder
16,17,1,29,Nurse,6.5,5,40,7,Normal Weight,132/87,80,4000,Sleep Apnea
17,18,0,29,Doctor,6.0,6,30,8,Normal,120/80,70,8000,Sleep Apnea
18,19,1,29,Nurse,6.5,5,40,7,Normal Weight,132/87,80,4000,Insomnia
19,20,0,30,Doctor,7.6,7,75,6,Normal,120/80,70,8000,No Disorder
20,21,0,30,Doctor,7.7,7,75,6,Normal,120/80,70,8000,No Disorder
21,22,0,30,Doctor,7.7,7,75,6,Normal,120/80,70,8000,No Disorder
22,23,0,30,Doctor,7.7,7,75,6,Normal,120/80,70,8000,No Disorder
23,24,0,30,Doctor,7.7,7,75,6,Normal,120/80,70,8000,No Disorder
24,25,0,30,Doctor,7.8,7,75,6,Normal,120/80,70,8000,No Disorder
25,26,0,30,Doctor,7.9,7,75,6,Normal,120/80,70,8000,No Disorder
26,27,0,30,Doctor,7.8,7,75,6,Normal,120/80,70,8000,No Disorder
27,28,0,30,Doctor,7.9,7,75,6,Normal,120/80,70,8000,No Disorder
28,29,0,30,Doctor,7.9,7,75,6,Normal,120/80,70,8000,No Disorder
29,30,0,30,Doctor,7.9,7,75,6,Normal,120/80,70,8000,No Disorder
30,31,1,30,Nurse,6.4,5,35,7,Normal Weight,130/86,78,4100,Sleep Apnea
31,32,1,30,Nurse,6.4,5,35,7,Normal Weight,130/86,78,4100,Insomnia
32,33,1,31,Nurse,7.9,8,75,4,Normal Weight,117/76,69,6800,No Disorder
33,34,0,31,Doctor,6.1,6,30,8,Normal,125/80,72,5000,No Disorder
34,35,0,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000,No Disorder
35,36,0,31,Doctor,6.1,6,30,8,Normal,125/80,72,5000,No Disorder
36,37,0,31,Doctor,6.1,6,30,8,Normal,125/80,72,5000,No Disorder
37,38,0,31,Doctor,7.6,7,75,6,Normal,120/80,70,8000,No Disorder
38,39,0,31,Doctor,7.6,7,75,6,Normal,120/80,70,8000,No Disorder
39,40,0,31,Doctor,7.6,7,75,6,Normal,120/80,70,8000,No Disorder
40,41,0,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000,No Disorder
41,42,0,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000,No Disorder
42,43,0,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000,No Disorder
43,44,0,31,Doctor,7.8,7,75,6,Normal,120/80,70,8000,No Disorder
44,45,0,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000,No Disorder
45,46,0,31,Doctor,7.8,7,75,6,Normal,120/80,70,8000,No Disorder
46,47,0,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000,No Disorder
47,48,0,31,Doctor,7.8,7,75,6,Normal,120/80,70,8000,No Disorder
48,49,0,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000,No Disorder
49,50,0,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000,Sleep Apnea

In [89]:
sleep_data['BMI Category'].value_counts()

BMI Category
Normal           195
Overweight       147
Normal Weight     21
Obese             10
Name: count, dtype: int64

In [90]:
sleep_data['BMI Category'] = sleep_data['BMI Category'].replace('Normal Weight', 'Normal')

In [91]:
sleep_data['BMI Category'].value_counts()

BMI Category
Normal        216
Overweight    147
Obese          10
Name: count, dtype: int64

In [92]:
group_sleep_disorder_by_gender = sleep_data.groupby('Gender')['Sleep Disorder'].value_counts().sort_index()
group_sleep_disorder_by_gender

Gender  Sleep Disorder
0       Insomnia           41
        No Disorder       137
        Sleep Apnea        11
1       Insomnia           36
        No Disorder        82
        Sleep Apnea        66
Name: count, dtype: int64

In [93]:
occupation_sleep_group = sleep_data.groupby('Occupation')['Sleep Duration'].mean()
occupation_sleep_group

Occupation
Accountant              7.113514
Doctor                  6.970423
Engineer                7.987302
Lawyer                  7.410638
Manager                 6.900000
Nurse                   7.048611
Sales Representative    5.900000
Salesperson             6.403125
Scientist               6.000000
Software Engineer       6.750000
Teacher                 6.690000
Name: Sleep Duration, dtype: float64

In [94]:
occupation_quality_sleep_group = sleep_data.groupby('Occupation')['Quality of Sleep'].mean()
occupation_quality_sleep_group

Occupation
Accountant              7.891892
Doctor                  6.647887
Engineer                8.412698
Lawyer                  7.893617
Manager                 7.000000
Nurse                   7.347222
Sales Representative    4.000000
Salesperson             6.000000
Scientist               5.000000
Software Engineer       6.500000
Teacher                 6.975000
Name: Quality of Sleep, dtype: float64

In [95]:
sleep_data.duplicated().any().sum()

0

In [96]:
sleep_data.columns

Index(['Person ID', 'Gender', 'Age', 'Occupation', 'Sleep Duration',
       'Quality of Sleep', 'Physical Activity Level', 'Stress Level',
       'BMI Category', 'Blood Pressure', 'Heart Rate', 'Daily Steps',
       'Sleep Disorder'],
      dtype='object')

In [97]:
columns_to_drop = [
    'Person ID',  'Quality of Sleep',
    'Blood Pressure', 'Heart Rate', 'Daily Steps','Sleep Disorder'
]

# Dropping the columns
sleep_data = sleep_data.drop(columns=columns_to_drop)

# Display the first few rows of the cleaned dataset
print(sleep_data.head())

   Gender  Age            Occupation  Sleep Duration  Physical Activity Level  \
0       0   27     Software Engineer             6.1                       42
1       0   28                Doctor             6.2                       60
2       0   28                Doctor             6.2                       60
3       0   28  Sales Representative             5.9                       30
4       0   28  Sales Representative             5.9                       30

   Stress Level BMI Category
0             6   Overweight
1             8       Normal
2             8       Normal
3             8        Obese
4             8        Obese

In [98]:
sleep_data.columns

Index(['Gender', 'Age', 'Occupation', 'Sleep Duration',
       'Physical Activity Level', 'Stress Level', 'BMI Category'],
      dtype='object')

Feature Engineering

In [99]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

features = ['Gender', 'Age', 'Occupation', 'Physical Activity Level', 'Stress Level', 'BMI Category']
target = 'Sleep Duration'

# 2. Preprocess the Data
# Encode categorical variables
label_encoders = {}
for column in ['Occupation', 'BMI Category']:
    le = LabelEncoder()
    sleep_data[column] = le.fit_transform(sleep_data[column])
    label_encoders[column] = le

# Split the data into features (X) and target (y)
X = sleep_data[features]
y = sleep_data[target]


# Normalize/Standardize the features
scaler = StandardScaler()
X = scaler.fit_transform(X)

     Gender  Age  Occupation  Physical Activity Level  Stress Level  \
0         0   27           9                       42             6
1         0   28           1                       60             8
2         0   28           1                       60             8
3         0   28           6                       30             8
4         0   28           6                       30             8
..      ...  ...         ...                      ...           ...
368       1   59           5                       75             3
369       1   59           5                       75             3
370       1   59           5                       75             3
371       1   59           5                       75             3
372       1   59           5                       75             3

     BMI Category
0               2
1               0
2               0
3               1
4               1
..            ...
368             2
369             2
370             2
371             2
372             2

[373 rows x 6 columns]

In [122]:
sleep_data.columns

Index(['Gender', 'Age', 'Occupation', 'Sleep Duration',
       'Physical Activity Level', 'Stress Level', 'BMI Category'],
      dtype='object')

In [126]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
# 3. Split the Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4. Choose and Train the Model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# 5. Evaluate the Model
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")

# 6. Make Predictions
# Example user input
new_user = pd.DataFrame({
    'Gender': [0],  # 0 for Male, 1 for Female (based on encoding)
    'Age': [27],
    'Occupation': [9],  # Coded value for Occupation
    'Physical Activity Level': [42],
    'Stress Level': [5],
    'BMI Category': [2]  # Coded value for BMI Category
})

# Preprocess new user input
new_user = scaler.transform(new_user)

# Predict sleep duration
predicted_sleep_duration = model.predict(new_user)
print(f"Predicted Sleep Duration: {predicted_sleep_duration[0]} hours")

Mean Squared Error: 0.005288363508863588
Predicted Sleep Duration: 6.326000000000002 hours

In [125]:
for column, le in label_encoders.items():
    print(f"Encoding for '{column}':")
    print(dict(zip(le.classes_, le.transform(le.classes_))))
    print()

Encoding for 'Occupation':
{'Accountant': 0, 'Doctor': 1, 'Engineer': 2, 'Lawyer': 3, 'Manager': 4, 'Nurse': 5, 'Sales Representative': 6, 'Salesperson': 7, 'Scientist': 8, 'Software Engineer': 9, 'Teacher': 10}

Encoding for 'BMI Category':
{'Normal': 0, 'Obese': 1, 'Overweight': 2}

# Data exploration of food

In [100]:
diet_nutri_data = pd.read_csv('dietNutri\FINAL FOOD DATASET\FOOD-DATA-GROUP5.csv')
diet_nutri_data.head()

,Unnamed: 0.1,Unnamed: 0,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
0,0,0,margarine with yoghurt,88,9.8,1.9,5.6,2.0,0.073,0.0,...,2.8,0.001,0.027,0.3,0.0,2.2,3.5,0.000,0.008,12.971
1,1,1,sunflower seed butter,99,8.8,0.7,6.2,1.6,3.700,1.7,...,10.2,0.300,0.700,49.8,0.3,106.6,92.2,0.075,0.800,27.500
2,2,2,hazelnut oil,120,13.6,1.0,10.6,1.4,0.000,0.0,...,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.000,0.000,13.600
3,3,3,menhaden fish oil,1966,218.0,66.3,58.2,74.5,0.000,0.0,...,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.000,0.000,218.000
4,4,4,cod liver fish oil,123,13.6,3.1,6.4,3.1,0.000,0.0,...,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.000,0.000,17.700

In [101]:
diet_nutri_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 722 entries, 0 to 721
Data columns (total 37 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0.1          722 non-null    int64
 1   Unnamed: 0            722 non-null    int64
 2   food                  722 non-null    object
 3   Caloric Value         722 non-null    int64
 4   Fat                   722 non-null    float64
 5   Saturated Fats        722 non-null    float64
 6   Monounsaturated Fats  722 non-null    float64
 7   Polyunsaturated Fats  722 non-null    float64
 8   Carbohydrates         722 non-null    float64
 9   Sugars                722 non-null    float64
 10  Protein               722 non-null    float64
 11  Dietary Fiber         722 non-null    float64
 12  Cholesterol           722 non-null    float64
 13  Sodium                722 non-null    float64
 14  Water                 722 non-null    float64
 15  Vitamin A             722 non-null    float64
 16  Vitamin B1            722 non-null    float64
 17  Vitamin B11           722 non-null    float64
 18  Vitamin B12           722 non-null    float64
 19  Vitamin B2            722 non-null    float64
 20  Vitamin B3            722 non-null    float64
 21  Vitamin B5            722 non-null    float64
 22  Vitamin B6            722 non-null    float64
 23  Vitamin C             722 non-null    float64
 24  Vitamin D             722 non-null    float64
 25  Vitamin E             722 non-null    float64
 26  Vitamin K             722 non-null    float64
 27  Calcium               722 non-null    float64
 28  Copper                722 non-null    float64
 29  Iron                  722 non-null    float64
 30  Magnesium             722 non-null    float64
 31  Manganese             722 non-null    float64
 32  Phosphorus            722 non-null    float64
 33  Potassium             722 non-null    float64
 34  Selenium              722 non-null    float64
 35  Zinc                  722 non-null    float64
 36  Nutrition Density     722 non-null    float64
dtypes: float64(33), int64(3), object(1)
memory usage: 208.8+ KB

In [102]:
diet_nutri_data.isnull().sum()

Unnamed: 0.1            0
Unnamed: 0              0
food                    0
Caloric Value           0
Fat                     0
Saturated Fats          0
Monounsaturated Fats    0
Polyunsaturated Fats    0
Carbohydrates           0
Sugars                  0
Protein                 0
Dietary Fiber           0
Cholesterol             0
Sodium                  0
Water                   0
Vitamin A               0
Vitamin B1              0
Vitamin B11             0
Vitamin B12             0
Vitamin B2              0
Vitamin B3              0
Vitamin B5              0
Vitamin B6              0
Vitamin C               0
Vitamin D               0
Vitamin E               0
Vitamin K               0
Calcium                 0
Copper                  0
Iron                    0
Magnesium               0
Manganese               0
Phosphorus              0
Potassium               0
Selenium                0
Zinc                    0
Nutrition Density       0
dtype: int64

In [103]:
diet_nutri_data = diet_nutri_data.drop(columns=['Unnamed: 0.1', 'Unnamed: 0'])
diet_nutri_data.head()

,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,Protein,Dietary Fiber,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
0,margarine with yoghurt,88,9.8,1.9,5.6,2.0,0.073,0.0,0.058,0.0,...,2.8,0.001,0.027,0.3,0.0,2.2,3.5,0.000,0.008,12.971
1,sunflower seed butter,99,8.8,0.7,6.2,1.6,3.700,1.7,2.800,0.9,...,10.2,0.300,0.700,49.8,0.3,106.6,92.2,0.075,0.800,27.500
2,hazelnut oil,120,13.6,1.0,10.6,1.4,0.000,0.0,0.000,0.0,...,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.000,0.000,13.600
3,menhaden fish oil,1966,218.0,66.3,58.2,74.5,0.000,0.0,0.000,0.0,...,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.000,0.000,218.000
4,cod liver fish oil,123,13.6,3.1,6.4,3.1,0.000,0.0,0.000,0.0,...,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.000,0.000,17.700

In [104]:
diet_data = pd.read_csv("diet/All_Diets.csv")
diet_data.head()

,Diet_type,Recipe_name,Cuisine_type,Protein(g),Carbs(g),Fat(g),Extraction_day,Extraction_time
0,paleo,Bone Broth From 'Nom Nom Paleo',american,5.22,1.29,3.20,2022-10-16,17:20:09
1,paleo,"Paleo Effect Asian-Glazed Pork Sides, A Sweet ...",south east asian,181.55,28.62,146.14,2022-10-16,17:20:09
2,paleo,Paleo Pumpkin Pie,american,30.91,302.59,96.76,2022-10-16,17:20:09
3,paleo,Strawberry Guacamole recipes,mexican,9.62,75.78,59.89,2022-10-16,17:20:09
4,paleo,"Asian Cauliflower Fried ""Rice"" From 'Nom Nom P...",chinese,39.84,54.08,71.55,2022-10-16,17:20:09

In [105]:
diet_data.columns

Index(['Diet_type', 'Recipe_name', 'Cuisine_type', 'Protein(g)', 'Carbs(g)',
       'Fat(g)', 'Extraction_day', 'Extraction_time'],
      dtype='object')

In [106]:
diet_data.isnull().sum()

Diet_type          0
Recipe_name        0
Cuisine_type       0
Protein(g)         0
Carbs(g)           0
Fat(g)             0
Extraction_day     0
Extraction_time    0
dtype: int64

In [107]:
diet_data.duplicated().value_counts()

False    7801
True        5
Name: count, dtype: int64

In [108]:
diet_data[diet_data.duplicated(keep=False) == True]
# Dropout duplicated and double check
diet_data = diet_data.drop_duplicates()

In [109]:
diet_data.duplicated().value_counts()

False    7801
Name: count, dtype: int64

In [110]:

diet_data['Cuisine_type'].unique()

array(['american', 'south east asian', 'mexican', 'chinese',
       'mediterranean', 'italian', 'french', 'indian', 'nordic',
       'eastern europe', 'central europe', 'kosher', 'british',
       'caribbean', 'south american', 'middle eastern', 'asian',
       'japanese', 'world'], dtype=object)

In [111]:
gym_data = pd.read_csv("gym/gym_exercise_dataset.csv")
gym_data.head()

,Exercise Name,Equipment,Variation,Utility,Mechanics,Force,Preparation,Execution,Target_Muscles,Synergist_Muscles,Stabilizer_Muscles,Antagonist_Muscles,Dynamic_Stabilizer_Muscles,Main_muscle,Difficulty (1-5),Secondary Muscles,parent_id
0,Neck Flexion,Cable,No,Basic or Auxiliary,Isolated,Pull,Sit on bench facing away from middle pulley. P...,Move head away from pulley by bending neck for...,"Sternocleidomastoid,","None,","Rectus Abdominis, Obliques,",NaN,NaN,Neck,2,Sternocleidomastoid,NaN
1,Neck Flexion,Lever (plate loaded),No,Basic or Auxiliary,Isolated,Pull,Sit on seat in machine. Position padded lever ...,Move head forward by flexing neck until chin t...,"Sternocleidomastoid,","None,","Latissimus Dorsi, Deltoid, Posterior, Rhomboid...",NaN,NaN,Neck,2,Sternocleidomastoid,NaN
2,Lateral Neck Flexion,Lever (plate loaded),No,Auxiliary,Isolated,Pull,Sit on seat in machine with feet apart . Pos...,Move head down to side by laterally flexing ne...,"Sternocleidomastoid,","Splenius, Erector Spinae, Levator Scapulae, Tr...","Latissimus Dorsi, Pectoralis Major, Sternal, P...",NaN,NaN,Neck,2,"Sternocleidomastoid, Levator Scapulae",NaN
3,Neck Flexion,Lever (selectorized),No,Basic or Auxiliary,Isolated,Pull,Sit on seat in machine. Position padded lever ...,Move head forward by flexing neck until chin t...,"Sternocleidomastoid,","None,","Latissimus Dorsi, Deltoid, Posterior, Rhomboid...",NaN,NaN,Neck,2,Sternocleidomastoid,NaN
4,Lateral Neck Flexion,Lever (selectorized),No,Auxiliary,Isolated,Pull,Sit on seat in machine with feet apart. Positi...,Move head down to side by laterally flexing ne...,"Sternocleidomastoid,","Splenius, Erector Spinae, Levator Scapulae, Tr...","Latissimus Dorsi, Pectoralis Major, Sternal, P...",NaN,NaN,Neck,2,"Sternocleidomastoid, Levator Scapulae",NaN

In [112]:
gym_data.columns

Index(['Exercise Name', 'Equipment', 'Variation', 'Utility', 'Mechanics',
       'Force', 'Preparation', 'Execution', 'Target_Muscles',
       'Synergist_Muscles', 'Stabilizer_Muscles', 'Antagonist_Muscles',
       'Dynamic_Stabilizer_Muscles', 'Main_muscle', 'Difficulty (1-5)',
       'Secondary Muscles', 'parent_id'],
      dtype='object')

In [113]:
gym_data.isnull().sum()

Exercise Name                   0
Equipment                       0
Variation                       4
Utility                         0
Mechanics                       0
Force                           0
Preparation                     0
Execution                       0
Target_Muscles                  0
Synergist_Muscles               2
Stabilizer_Muscles            128
Antagonist_Muscles            476
Dynamic_Stabilizer_Muscles    352
Main_muscle                     0
Difficulty (1-5)                0
Secondary Muscles               1
parent_id                     456
dtype: int64

In [114]:
# gym_data['Variation'].fillna('No', inplace=True)
gym_data['parent_id'].fillna(0, inplace=True)

In [115]:
columns_to_drop = [
    'Variation', 'Synergist_Muscles', 'Stabilizer_Muscles',
    'Antagonist_Muscles', 'Dynamic_Stabilizer_Muscles', 'parent_id'
]

# Dropping the columns
gym_data = gym_data.drop(columns=columns_to_drop)

# Display the first few rows of the cleaned dataset
print(gym_data.head())

          Exercise Name             Equipment             Utility Mechanics  \
0          Neck Flexion                 Cable  Basic or Auxiliary  Isolated
1          Neck Flexion  Lever (plate loaded)  Basic or Auxiliary  Isolated
2  Lateral Neck Flexion  Lever (plate loaded)           Auxiliary  Isolated
3          Neck Flexion  Lever (selectorized)  Basic or Auxiliary  Isolated
4  Lateral Neck Flexion  Lever (selectorized)           Auxiliary  Isolated

  Force                                        Preparation  \
0  Pull  Sit on bench facing away from middle pulley. P...
1  Pull  Sit on seat in machine. Position padded lever ...
2  Pull  Sit on seat in machine with feet apart   . Pos...
3  Pull  Sit on seat in machine. Position padded lever ...
4  Pull  Sit on seat in machine with feet apart. Positi...

                                           Execution        Target_Muscles  \
0  Move head away from pulley by bending neck for...  Sternocleidomastoid,
1  Move head forward by flexing neck until chin t...  Sternocleidomastoid,
2  Move head down to side by laterally flexing ne...  Sternocleidomastoid,
3  Move head forward by flexing neck until chin t...  Sternocleidomastoid,
4  Move head down to side by laterally flexing ne...  Sternocleidomastoid,

  Main_muscle  Difficulty (1-5)                      Secondary Muscles
0        Neck                 2                    Sternocleidomastoid
1        Neck                 2                    Sternocleidomastoid
2        Neck                 2  Sternocleidomastoid, Levator Scapulae
3        Neck                 2                    Sternocleidomastoid
4        Neck                 2  Sternocleidomastoid, Levator Scapulae

In [116]:
gym_data.isnull().sum()

Exercise Name        0
Equipment            0
Utility              0
Mechanics            0
Force                0
Preparation          0
Execution            0
Target_Muscles       0
Main_muscle          0
Difficulty (1-5)     0
Secondary Muscles    1
dtype: int64

In [117]:
stretch_data.isnull().sum()

Exercise Name         1
Equipment             1
Preparation           6
Execution             6
Target_Muscles        1
Synergist_Muscles    41
Main_muscle           0
dtype: int64

In [118]:
stretch_data.head()

,Exercise Name,Equipment,Preparation,Execution,Target_Muscles,Synergist_Muscles,Main_muscle
0,Retraction​​​​​​​,Stretch,Stand or sit.,Pull head back as far possible while looking s...,"Longus colli,","Splenius, Trapezius, Upper, Erector Spinae, Ce...",Neck
1,Neck Extensor,Stretch,Bow head forward with jaw shut. Depress chin i...,Slightly turn head to one side. Hold stretch. ...,"Splenius,","Trapezius, Upper (Part 1), Erector Spinae, Cer...",Neck
2,Doorway,Stretch,NaN,NaN,"Deltoid, Anterior,","Pectoralis Major, Sternal, Pectoralis Major, C...",Shoulder
3,Wall,Stretch,NaN,NaN,"Deltoid, Anterior,","Pectoralis Major, Sternal, Pectoralis Major, C...",Shoulder
4,Side Deltoid,Stretch,NaN,NaN,"Deltoid, Lateral,","Infraspinatus, Teres Minor, Trapezius, Middle,...",Shoulder

In [119]:
columns_to_drop = [
  'Synergist_Muscles', 
]

# Dropping the columns
stretch_data = stretch_data.drop(columns=columns_to_drop)

In [120]:
# drop na
stretch_data = stretch_data.dropna()
stretch_data.isnull().sum()

Exercise Name     0
Equipment         0
Preparation       0
Execution         0
Target_Muscles    0
Main_muscle       0
dtype: int64

In [121]:
stretch_data.head()

,Exercise Name,Equipment,Preparation,Execution,Target_Muscles,Main_muscle
0,Retraction​​​​​​​,Stretch,Stand or sit.,Pull head back as far possible while looking s...,"Longus colli,",Neck
1,Neck Extensor,Stretch,Bow head forward with jaw shut. Depress chin i...,Slightly turn head to one side. Hold stretch. ...,"Splenius,",Neck
6,Overhead​​​​​​​,Stretch,Put one arm overhead. Position forearm as clos...,Pull elbow back and toward head. Hold stretch....,"Triceps, Long Head,",Upper Arms
7,Towel,Stretch,Grasp near end of towel or rope. Position towe...,Pull towel downward with lower arm. Hold stret...,"Triceps, Long Head,",Upper Arms
8,Doorway,Stretch,Stand at end of wall or in doorway facing perp...,Turn body away from positioned arm. Hold stret...,"Biceps Brachii,",Upper Arms